pipeline {
    agent any
    
    stages {
        stage("Checkout") {
            steps {
                git branch: 'main', credentialsId: 'ci-key', url: 'git@github.com:jdolak/plnd4u.git'
            }
        }
        stage("Setup Test Env") {
            steps {
                sh 'echo "MYSQL_ROOT_PASSWORD=test" > ./src/.env'
                sh 'echo "PEPPER=test" >> ./src/.env'
                sh 'pip install -r ./docker/requirements.txt'
            }
        }
        stage("Build") {
            steps {
                sh 'make configure'
            }
        }
        stage("Test") {
            steps {
                sh 'python3 ./tests/integration-tests.py'
            }
        }
        stage("Deploy") {
            steps {
                sh 'make deploy'
            }
        }
    }
    post {
        always {
            sh 'make down'
        }
    }
}
