version: '3.1'

services: 
  flask-python:
    image: plnd4u-image
    ports:
      - ${HOST_PORT}:${PORT}
    restart: on-failure
    deploy:
      resources:    
        limits:
          memory: 200MB

  db:
    image: mysql
    command: --secure-file-priv=/mnt/data --default-authentication-plugin=mysql_native_password 
    restart: no
    ports: 
      - 3306:3306
    env_file: ../src/.env
    volumes:
      - mysqldata:/var/lib/mysql
      - ../data/dump.sql:/mnt/data/dump.sql
      #- ../data:/mnt/data
      - ./my.cnf:/etc/my.cnf
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    deploy:
      resources:    
        limits:
          memory: 750MB

volumes:
  mysqldata:
