version: '3.1'

services: 
  flask-python:
    image: plnd4u-image
    ports:
      - 80:80
    restart: no
    deploy:
      resources:    
        limits:
          memory: 200MB

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=/mnt/data
    restart: no
    ports: 
      - 9123:3306
    environment:
      MYSQL_ROOT_PASSWORD: goirish
    volumes:
      - mysqldata:/var/lib/mysql
      - ../data:/mnt/data
    deploy:
      resources:    
        limits:
          memory: 450MB

volumes:
  mysqldata:
