version: '3.1'

services: 
  flask-python:
    image: plnd4u-image
    ports:
      - 80:80
    restart: no

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: no
    ports: 
      - 9123:3306
    environment:
      MYSQL_ROOT_PASSWORD: goirish
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
