version: '3.1'

services:
  # bot-db:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} 
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #   volumes:
  #     - mongodata:/data/db
    
  bot-python:
    #image: plnd4u-image
    image: nginx
    ports:
      - 80:80
      - 8080:8080
    restart: always
#volumes:
#  mongodata:
