---
- name: plnd4u website config
  hosts: plnd4u-1
  tasks:
   - name: Pull source code from repository
     git:
       repo: git@github.com:jdolak/plnd4u.git
       dest: /home/plnd4u-admin/plnd4u/
   - name: Run web server
     shell:
       cmd: make up
       chdir: ~/plnd4u
